############################   trainer ####################################
gpus: '0'
save_dir: /root/autodl-tmp/VAE_pytorchLightning/模型参数保存
num_workers: 4
precision: 32
max_epochs: 1000

############################   model ####################################
model_type: model5
batch_size: 256
version: 1
############################ optimizer ##################################
optim: Adam                          # 可选优化器Adam、SGD
lr: 1e-4                             # 学习率
lr_scheduler: None      # 可选CosineAnnealingLR、OneCycleLR、None

############################ load checkpoint path ###################
checkpoint_path:

############################ dataset ##################################
dataset_name: 'Spam'
train_data: /root/autodl-tmp/VAE_pytorchLightning/Spam_标签置换后train.csv
val_data: /root/autodl-tmp/VAE_pytorchLightning/Spam_标签置换后test.csv
pro_type_file: /root/autodl-tmp/VAE_pytorchLightning/Spam_pro_type.pkl
dim: 57            # 数据特征维度
# nhead: 3           # 多头注意力机制的头数
missing_ratio: 0.3 # 模拟缺失比率
data_norm: minmax_norm # 数据标准化方式

