############################   trainer ####################################
gpus: '0'
save_dir: /root/autodl-tmp/VAE_pytorchLightning/模型参数保存
num_workers: 4
precision: 32
max_epochs: 1000

############################   model ####################################
batch_size: 256
version: 2
############################ optimizer ##################################
optim: Adam                          # 可选优化器Adam、SGD
lr: 1e-4                             # 学习率
lr_scheduler: CosineAnnealingLR      # 可选CosineAnnealingLR、OneCycleLR、None

############################ load checkpoint path ###################
checkpoint_path: 

############################ dataset ##################################
dataset_name: 'Letter'
train_data: /root/autodl-tmp/VAE_pytorchLightning/Letter_train.csv
val_data: /root/autodl-tmp/VAE_pytorchLightning/Letter_test.csv
dim: 16            # 数据特征维度
nhead: 4           # 多头注意力机制的头数
missing_ratio: 0.3 # 模拟缺失比率
data_norm: minmax_norm # 数据标准化方式

