############################   trainer ####################################
gpus: [1]  # [0,2]
save_dir: /userhome/wangyuanquan/WYQ/VAE_pytorchLightning/模型参数保存
num_workers: 4
precision: 32
max_epochs: 1000

############################   model ####################################
model_type: model5
batch_size: 256
version: 2
############################ optimizer ##################################
optim: Adam                          # 可选优化器Adam、SGD
lr: 1e-5                             # 学习率
lr_scheduler: CosineAnnealingLR      # 可选CosineAnnealingLR、OneCycleLR、None

############################ load checkpoint path ###################
checkpoint_path:

############################ dataset ##################################
dataset_name: 'Breast'
train_data: /userhome/wangyuanquan/WYQ/VAE_pytorchLightning/Breast/Breast模拟缺失_0_3.csv
valid_data: /userhome/wangyuanquan/WYQ/VAE_pytorchLightning/Breast/Breast_without_label.csv
pro_type_file: /userhome/wangyuanquan/WYQ/VAE_pytorchLightning/Breast/Breast_pro_type.pkl
replace_dict_file: /userhome/wangyuanquan/WYQ/VAE_pytorchLightning/Breast/Breast数值置换表.pkl
dim: 9            # 数据特征维度
# nhead: 3           # 多头注意力机制的头数
data_norm: minmax_norm # 数据标准化方式

