############################   trainer ####################################
gpus: '0'
save_dir: C:\王源权\西南财经大学\硕士毕业论文\模型代码\VAE_pytorchLightning\模型参数保存
num_workers: 4
precision: 32
max_epochs: 1000

############################   model ####################################
model_type: model5
batch_size: 256
version: 1
############################ optimizer ##################################
optim: Adam                          # 可选优化器Adam、SGD
lr: 1e-5                             # 学习率
lr_scheduler: CosineAnnealingLR      # 可选CosineAnnealingLR、OneCycleLR、None

############################ load checkpoint path ###################
checkpoint_path: 

############################ dataset ##################################
dataset_name: 'Spam'
train_data: C:\王源权\西南财经大学\硕士毕业论文\模型代码\VAE_pytorchLightning\Spam\Spam模拟缺失_0_3.csv
pro_type_file: C:\王源权\西南财经大学\硕士毕业论文\模型代码\VAE_pytorchLightning\Spam\Spam_pro_type.pkl
replace_dict_file: C:\王源权\西南财经大学\硕士毕业论文\模型代码\VAE_pytorchLightning\Spam\Spam数值置换表.pkl
dim: 57            # 数据特征维度
# nhead: 3           # 多头注意力机制的头数
data_norm: minmax_norm # 数据标准化方式

